name: Deploy React App to Ubuntu Server

on:
  push:
    branches:
      - main   # or your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20' # match your server Node version

    - name: Install dependencies
      run: |
        cd frontend
        npm ci

    - name: Build React app
      run: |
        cd frontend
        npm run build

    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          rm -rf /var/www/html/hackyeah2025/*
          cp -r /home/ubuntu/hackyeah2025/frontend/build/* /var/www/html/hackyeah2025/
          chown -R www-data:www-data /var/www/html/hackyeah2025
          chmod -R 755 /var/www/html/hackyeah2025
          systemctl reload nginx
